version: '3.8'
services:
  web:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
